
package org.jgroups.util;

/**
 * Dumps the data (tests.data) generated by {@link JUnitXMLReporter} to stdout
 * 
 * @author Bela Ban
 * @since 3.1
 */
public class DumpData {

  public static void main(String[] args) {
    // dependencies to testng removed
  }

}
